# node version specified via .nvmrc
language: node_js

# speed up builds by caching node modules
cache:
  directories:
    - node_modules

# turn off email notifications
notifications:
  email: false

before_script:
  - npm prune

# build tasks
script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - npm run corp-semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
